version: '3'

services:
  neo4j:
    image: neo4j:5.17.0-community-bullseye
    container_name: my_neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
      - neo4j-log:/logs
    networks:
      - mynetwork

  java:
    build:
      context: ./infra
      dockerfile: Dockerfile
    container_name: maven_and_gradle_java
    tty: true
    volumes:
      - ./:/home
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-log: